---
language: rust
cache: cargo
sudo: false
rust:
  - nightly
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --release --verbose --all
  - cargo test --verbose --all
