[package]
name = "hcl-parser"
version = "0.1.0"
authors = ["Adrien Thebo <adrien@lagrange-automation.io>"]

[dependencies]
log = "0.4"
env_logger = "0.5"
serde_json = "1.0"

[dependencies.nom]
version = ">= 4.1.1"
features = ["verbose-errors"]
